# Generated by Django 6.0.3 on 2026-04-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("src_ip", models.GenericIPAddressField()),
                ("dest_ip", models.GenericIPAddressField()),
                ("src_port", models.IntegerField(blank=True, null=True)),
                ("dest_port", models.IntegerField(blank=True, null=True)),
                ("protocol", models.CharField(blank=True, max_length=10)),
                ("signature", models.CharField(max_length=500)),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "High"), (2, "Medium"), (3, "Low"), (4, "Info")],
                        default=3,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=255)),
                ("raw_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_ip", models.GenericIPAddressField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("alert_count", models.IntegerField(default=0)),
                ("cvss_score", models.FloatField(blank=True, null=True)),
                ("technique_id", models.CharField(blank=True, max_length=20)),
                ("technique_name", models.CharField(blank=True, max_length=255)),
                ("ai_summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewing", "Reviewing"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("alerts", models.ManyToManyField(blank=True, to="core.alert")),
            ],
        ),
    ]
