# Generated by Django 6.0.3 on 2026-04-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['src_ip', 'timestamp', 'signature'], name='core_alert_src_ip_912def_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['src_ip', 'status', 'start_time'], name='core_incide_src_ip_e9bae8_idx'),
        ),
    ]
